### ISSUE TITLE
No such file

### ISSUE THREAD

**Issue by Pavel71** [voximplant/ios-sdk-releases#1]
Hi! Version 2.50.0 When I try to launch UnitTests, I will get this error and test Failed. If I use version 2.47.1 everything is ok. Where could be a problem? Thank you.
'/Library/Developer/CoreSimulator/Volumes/iOS_21A328/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/VoximplantWebRTC.framework/VoximplantWebRTC' (no such file))

**Comment by YesVladess** [comment]
Hello!

I wasn't able to reproduce your problem with SDK version 2.50.0, however, there are some advices that can help you to resolve your issue.

1) Delete DerivedData
2) Xcode: File -> Packages -> Reset Package Caches
3) Your unit test target -> Build Phases -> Target Dependencies -> Check if our SDK is present there, so unit test target can use it.

Hope this helps!
